export default {
  common: {
    confirm: 'Confirm',
    cancel: 'Cancel',
    save: 'Save',
    delete: 'Delete',
    edit: 'Edit',
    add: 'Add',
    search: 'Search',
    reset: 'Reset',
    export: 'Export',
    import: 'Import',
    back: 'Back',
    loading: 'Loading...',
    noData: 'No Data',
    success: 'Success',
    failed: 'Failed',
    developing: 'Under Development...'
  },
  login: {
    title: 'ZheHang ERP',
    subtitle: 'Intelligent Enterprise Resource Management',
    username: 'Username',
    password: 'Password',
    captcha: 'Captcha',
    rememberMe: 'Remember Me',
    login: 'Login',
    forgotPassword: 'Forgot Password?'
  },
  menu: {
    dashboard: 'Dashboard',
    cockpit: 'Cockpit',
    system: 'System',
    user: 'Users',
    role: 'Roles',
    menuMgt: 'Menus',
    loginLog: 'Login Log',
    operLog: 'Operation Log',
    notification: 'Notifications',
    org: 'Organization',
    dept: 'Department',
    post: 'Position',
    employee: 'Employee',
    structure: 'Org Chart',
    crm: 'CRM',
    lead: 'Leads',
    customer: 'Customers',
    contact: 'Contacts',
    opportunity: 'Opportunities',
    contract: 'Contracts',
    hrm: 'HRM',
    recruit: 'Recruitment',
    attendance: 'Attendance',
    salary: 'Salary',
    performance: 'Performance',
    finance: 'Finance',
    voucher: 'Vouchers',
    ledger: 'Ledger',
    report: 'Reports',
    tax: 'Tax',
    invoice: 'Invoice',
    reimburse: 'Reimbursement',
    project: 'Projects',
    projectList: 'Project List',
    gantt: 'Gantt Chart',
    board: 'Board',
    supply: 'Supply Chain',
    vendor: 'Vendors',
    purchase: 'Purchase',
    receipt: 'Receipt',
    sales: 'Sales',
    quotation: 'Quotation',
    order: 'Orders',
    delivery: 'Delivery',
    salesReceipt: 'Payment',
    workflow: 'Workflow',
    designer: 'Designer',
    todo: 'Todo',
    done: 'Done',
    started: 'My Started',
    file: 'Files & Knowledge',
    fileManager: 'File Manager',
    kb: 'Knowledge Base',
    article: 'Articles',
    reportCenter: 'Report Center',
    reportDesigner: 'Report Designer',
    reportList: 'Report List',
    multidim: 'Multi-Table',
    aiChat: 'AI Assistant'
  },
  ai: {
    title: 'AI Assistant',
    placeholder: 'Type your question...',
    send: 'Send',
    thinking: 'AI is thinking...',
    welcome: 'Hello! I am ZheHang AI Assistant. How can I help you?'
  },
  org: {
    deptTree: 'Department List',
    searchDept: 'Search Department',
    deptName: 'Department Name',
    parentDept: 'Parent Department',
    selectParentDept: 'Select Parent Department',
    inputDeptName: 'Enter Department Name',
    leader: 'Leader',
    inputLeader: 'Enter Leader',
    phone: 'Phone',
    inputPhone: 'Enter Phone',
    email: 'Email',
    inputEmail: 'Enter Email',
    sort: 'Sort',
    inputSort: 'Enter Sort',
    status: 'Status',
    statusNormal: 'Normal',
    statusDisabled: 'Disabled',
    selectStatus: 'Select Status',
    subDepts: 'Sub Departments',
    selectDeptTip: 'Click on a department to view details',
    addDept: 'Add Department',
    editDept: 'Edit Department',
    confirmDeleteDept: 'Are you sure to delete this department?',
    deptDetail: 'Department Detail',
    memberCount: 'Member Count',
    postCode: 'Post Code',
    postName: 'Post Name',
    inputPostCode: 'Enter Post Code',
    inputPostName: 'Enter Post Name',
    headcount: 'Headcount',
    responsibilities: 'Responsibilities',
    inputResponsibilities: 'Enter Responsibilities',
    createTime: 'Create Time',
    actions: 'Actions',
    addPost: 'Add Position',
    editPost: 'Edit Position',
    confirmDeletePost: 'Are you sure to delete this position?',
    empCode: 'Employee ID',
    empName: 'Employee Name',
    inputEmpCode: 'Enter Employee ID',
    inputEmpName: 'Enter Employee Name',
    selectDept: 'Select Department',
    selectPost: 'Select Position',
    empStatusActive: 'Active',
    empStatusTrial: 'Probation',
    empStatusLeft: 'Left',
    gender: 'Gender',
    male: 'Male',
    female: 'Female',
    birthDate: 'Birth Date',
    idCard: 'ID Card',
    address: 'Address',
    hireDate: 'Hire Date',
    regularDate: 'Regular Date',
    contractStart: 'Contract Start',
    contractEnd: 'Contract End',
    education: 'Education',
    university: 'University',
    major: 'Major',
    emergencyContact: 'Emergency Contact',
    emergencyPhone: 'Emergency Phone',
    tabBasic: 'Basic Info',
    tabPosition: 'Position Info',
    tabContract: 'Contract Info',
    tabEducation: 'Education',
    tabEmergency: 'Emergency Contact',
    addEmployee: 'Add Employee',
    editEmployee: 'Edit Employee',
    confirmDeleteEmployee: 'Are you sure to delete this employee?',
    empDetail: 'Employee Detail'
  }
}
