export default {
  common: {
    confirm: 'Confirm',
    cancel: 'Cancel',
    save: 'Save',
    delete: 'Delete',
    edit: 'Edit',
    add: 'Add',
    search: 'Search',
    reset: 'Reset',
    export: 'Export',
    import: 'Import',
    back: 'Back',
    loading: 'Loading...',
    noData: 'No Data',
    success: 'Success',
    failed: 'Failed',
    developing: 'Under Development...',
    viewAll: 'View All',
    markRead: 'Mark Read',
    markAllRead: 'Mark All Read',
    more: 'More',
    close: 'Close',
    send: 'Send',
    refresh: 'Refresh',
    today: 'Today',
    total: 'Total'
  },
  login: {
    title: 'ZheHang ERP',
    subtitle: 'Intelligent Enterprise Resource Management',
    username: 'Username',
    password: 'Password',
    captcha: 'Captcha',
    rememberMe: 'Remember Me',
    login: 'Login',
    forgotPassword: 'Forgot Password?'
  },
  menu: {
    dashboard: 'Dashboard',
    cockpit: 'Cockpit',
    system: 'System',
    user: 'Users',
    role: 'Roles',
    menuMgt: 'Menus',
    loginLog: 'Login Log',
    operLog: 'Operation Log',
    notification: 'Notifications',
    org: 'Organization',
    dept: 'Department',
    post: 'Position',
    employee: 'Employee',
    structure: 'Org Chart',
    crm: 'CRM',
    lead: 'Leads',
    customer: 'Customers',
    contact: 'Contacts',
    opportunity: 'Opportunities',
    contract: 'Contracts',
    hrm: 'HRM',
    recruit: 'Recruitment',
    attendance: 'Attendance',
    salary: 'Salary',
    performance: 'Performance',
    finance: 'Finance',
    voucher: 'Vouchers',
    ledger: 'Ledger',
    report: 'Reports',
    tax: 'Tax',
    invoice: 'Invoice',
    reimburse: 'Reimbursement',
    project: 'Projects',
    projectList: 'Project List',
    gantt: 'Gantt Chart',
    board: 'Board',
    supply: 'Supply Chain',
    vendor: 'Vendors',
    purchase: 'Purchase',
    receipt: 'Receipt',
    sales: 'Sales',
    quotation: 'Quotation',
    order: 'Orders',
    delivery: 'Delivery',
    salesReceipt: 'Payment',
    workflow: 'Workflow',
    designer: 'Designer',
    todo: 'Todo',
    done: 'Done',
    started: 'My Started',
    file: 'Files & Knowledge',
    fileManager: 'File Manager',
    kb: 'Knowledge Base',
    article: 'Articles',
    reportCenter: 'Report Center',
    reportDesigner: 'Report Designer',
    reportList: 'Report List',
    multidim: 'Multi-Table',
    aiChat: 'AI Assistant'
  },
  ai: {
    title: 'AI Assistant',
    placeholder: 'Type your question...',
    send: 'Send',
    thinking: 'AI is thinking...',
    welcome: 'Hello! I am ZheHang AI Assistant. How can I help you?',
    newChat: 'New Chat',
    history: 'Chat History',
    clearHistory: 'Clear History',
    quickCommands: 'Quick Commands',
    analyzeData: 'Analyze Today Data',
    generateReport: 'Generate Daily Report',
    exportCustomer: 'Export Customer List',
    fullscreen: 'Fullscreen Chat',
    copySuccess: 'Copied to clipboard',
    noHistory: 'No chat history',
    inputTip: 'Type a question, press Enter to send',
    exampleQuestions: 'Try asking me these questions',
    example1: 'What are my tasks for today?',
    example2: 'How is this month sales performance?',
    example3: 'Analyze customer follow-up status'
  },
  dashboard: {
    welcome: {
      morning: 'Good Morning',
      afternoon: 'Good Afternoon',
      evening: 'Good Evening'
    },
    stats: {
      todoCount: 'Today Todo',
      approvalCount: 'Pending Approval',
      customerFollow: 'Customer Follow',
      monthlyPerf: 'Monthly Performance'
    },
    shortcut: 'Quick Navigation',
    todoList: 'Todo List',
    notice: 'Notices',
    schedule: 'Schedule',
    recentVisit: 'Recent Visits',
    noTodo: 'No pending items',
    noNotice: 'No notices',
    noRecentVisit: 'No recent visits',
    priority: {
      high: 'Urgent',
      medium: 'Normal',
      low: 'Low'
    },
    todoType: {
      approval: 'Approval',
      task: 'Task',
      follow: 'Follow',
      other: 'Other'
    }
  },
  workflow: {
    processList: 'Process List',
    processName: 'Process Name',
    processKey: 'Process Key',
    category: 'Category',
    version: 'Version',
    status: 'Status',
    description: 'Description',
    design: 'Design',
    publish: 'Publish',
    disable: 'Disable',
    enable: 'Enable',
    draft: 'Draft',
    published: 'Published',
    disabled: 'Disabled',
    createProcess: 'New Process',
    editProcess: 'Edit Process',
    designer: 'Process Designer',
    formConfig: 'Form Config',
    processConfig: 'Process Config',
    nodeConfig: 'Node Config',
    nodeName: 'Node Name',
    nodeType: 'Node Type',
    assignee: 'Assignee',
    assigneeType: 'Assignee Type',
    specifyUser: 'Specify User',
    specifyRole: 'Specify Role',
    deptLeader: 'Dept Leader',
    approvalType: 'Approval Type',
    countersign: 'Countersign',
    orSign: 'Or-Sign',
    sequential: 'Sequential',
    conditionBranch: 'Condition Branch',
    addCondition: 'Add Condition',
    conditionField: 'Condition Field',
    conditionOp: 'Operator',
    conditionValue: 'Value',
    addNode: 'Add Node',
    startNode: 'Start',
    endNode: 'End',
    approvalNode: 'Approval Node',
    conditionNode: 'Condition Node',
    templates: 'Templates',
    leaveApproval: 'Leave Approval',
    expenseApproval: 'Expense Approval',
    purchaseApproval: 'Purchase Approval',
    sealApproval: 'Seal Approval',
    useTemplate: 'Use Template',
    todo: 'My Todo',
    done: 'My Done',
    started: 'My Started',
    instanceTitle: 'Title',
    initiator: 'Initiator',
    initiateTime: 'Initiated At',
    currentNode: 'Current Node',
    handleTime: 'Handled At',
    myAction: 'My Action',
    currentHandler: 'Current Handler',
    approve: 'Approve',
    reject: 'Reject',
    transfer: 'Transfer',
    revoke: 'Revoke',
    viewDetail: 'View Detail',
    approveDialog: 'Approval',
    comment: 'Comment',
    commentPlaceholder: 'Enter your comment',
    transferTo: 'Transfer to',
    selectUser: 'Select User',
    formData: 'Form Data',
    approvalTrack: 'Approval Track',
    startProcess: 'Start Process',
    selectProcess: 'Select Process',
    fillForm: 'Fill Form',
    submitProcess: 'Submit',
    actionStart: 'Started',
    actionApprove: 'Approved',
    actionReject: 'Rejected',
    actionTransfer: 'Transferred',
    actionCancel: 'Cancelled',
    statusProcessing: 'Processing',
    statusCompleted: 'Completed',
    statusRejected: 'Rejected',
    statusCancelled: 'Cancelled',
    noTodo: 'No pending tasks',
    noDone: 'No completed tasks',
    noStarted: 'No started processes',
    confirmPublish: 'Confirm to publish this process? It will be available for use after publishing.',
    confirmDisable: 'Confirm to disable this process? No new approvals can be initiated after disabling.',
    confirmCancel: 'Confirm to cancel this process?',
    leaveType: 'Leave Type',
    leaveDays: 'Days',
    leaveReason: 'Reason',
    expenseAmount: 'Amount',
    expenseType: 'Expense Type',
    expenseDesc: 'Description',
    purchaseItem: 'Item',
    purchaseAmount: 'Amount',
    purchaseQty: 'Quantity',
    purchaseReason: 'Reason',
    sealType: 'Seal Type',
    sealUsage: 'Usage',
    sealCopies: 'Copies'
  },
  notification: {
    title: 'Notification Center',
    all: 'All',
    unread: 'Unread',
    system: 'System',
    approval: 'Approval',
    task: 'Task',
    message: 'Message',
    markRead: 'Mark Read',
    markAllRead: 'Mark All Read',
    delete: 'Delete',
    batchDelete: 'Batch Delete',
    noNotification: 'No notifications',
    settings: 'Settings',
    settingsTitle: 'Notification Settings',
    emailNotify: 'Email Notification',
    browserNotify: 'Browser Notification',
    frequency: 'Notification Frequency',
    realtime: 'Real-time',
    daily: 'Daily Digest',
    weekly: 'Weekly Digest',
    tabs: {
      notification: 'Notifications',
      message: 'Messages',
      todo: 'Todo'
    }
  }
}
